CREATE TABLE FEED(
    ID BIGINT AUTO_INCREMENT,
    DESCRIPTION VARCHAR(2048),
    GUID VARCHAR(255),
    IMAGE_URL VARCHAR(255),
    PUBLICATION_DATE TIMESTAMP,
    TITLE VARCHAR(255)
);

CREATE INDEX PUB_DATE_INDEX ON FEED(PUBLICATION_DATE);
ALTER TABLE FEED ADD CONSTRAINT GUID_INDEX UNIQUE(GUID);